apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flywait.fullname" . }}-config
  labels:
    heritage: {{ .Release.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "flywait.name" . }}
data:
  {{- if .Values.data }}
    {{- range $key, $value := .Values.data }}
    {{ $key }}: |
    {{ $value | indent 4 }}
    {{- end -}}
    {{- end -}}
